{% set name = "qxub" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - qxub=qxub.cli:qxub
    - qx=qxub.config.aliases:qx_main
    - qxtat=qxub.config.aliases:qxtat_main
    - qxet=qxub.config.aliases:qxet_main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - click
    - tailer
    - rich
    - omegaconf
    - pyyaml
    - requests

test:
  imports:
    - qxub
    - qxub.cli
    - qxub.config
    - qxub.platform
    - qxub.execution
    - qxub.resources
  commands:
    - qxub --help
    - qxub --version
    - qx --help
    - qxub exec --help
    - qxub config --help
    - qxub platform --help

about:
  home: https://github.com/swarbricklab/qsub_tools
  license: MIT
  license_file: LICENSE
  summary: Simplified job submission to HPC systems via PBS Pro
  description: |
    qxub is a sophisticated PBS job submission wrapper designed for HPC
    environments. It eliminates the boilerplate and complexity of writing
    PBS job scripts by providing a unified command-line interface for
    submitting jobs across different execution contexts. Whether you need
    to run code in conda environments, with environment modules, inside
    containers, or as direct submissions, qxub handles the PBS integration
    seamlessly while offering intelligent queue selection, resource
    management, and comprehensive configuration options.
  doc_url: https://github.com/swarbricklab/qsub_tools/blob/main/README.md
  dev_url: https://github.com/swarbricklab/qsub_tools

extra:
  recipe-maintainers:
    - swarbricklab
