name: Code Formatting

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
        with:
          python-version: 3.9
          auto-update-conda: true
          environment-file: environment.dev.yaml
          activate-environment: test

      - name: Check code formatting with Black
        shell: bash -el {0}
        run: |
          black --check --diff $(git ls-files '*.py')
